'use strict';
const assert=require('assert'),vm=require('vm');
const {harness,root}=require('./simulation-harness.cjs'),E=require('../game-engine'),{DAYBREAK_ROLES,ARTIFACTS}=require('../public/daybreak-info');
let checks=0,games=0;const coverage=new Set(),copies=new Set();
function setup(deck,seed=1,bots=false){const h=harness(seed),n=deck.length-3,cs=[h.client('P0')],code=cs[0].call('room:create',{name:'P0'}).code;assert(cs[0].call('room:setPlayerCount',{count:n}).ok);if(bots)cs[0].call('room:addBot',{fill:true});else for(let i=1;i<n;i++){cs.push(h.client('P'+i));assert(cs[i].call('room:join',{code,name:'P'+i}).ok)}h.setDeck(deck);assert(cs[0].call('room:setRoles',{roles:deck}).ok);assert(cs[0].call('game:start').ok);return {h,cs,room:h.room(code),code};}
function act(g,index,role,payload,wrapper=role){let res;g.h.ctx.r=g.room;g.h.ctx.actor=g.room.players[index];g.h.ctx.payload=payload;g.h.ctx.actionRole=role;g.h.ctx.wrapper=wrapper;g.h.ctx.cb=x=>res=x;g.room.phase='night';g.room.actionWindowOpen=true;g.room.pendingActors=new Set([g.room.players[index].id]);g.room.awaitingAck=new Set();vm.runInContext('performRoleAction(r,actor,actionRole,payload,cb,wrapper)',g.h.ctx);assert(res?.ok);checks++;return res;}
function prompt(g,i,role,wrapper=role){g.h.ctx.r=g.room;g.h.ctx.actor=g.room.players[i];g.h.ctx.actionRole=role;g.h.ctx.wrapper=wrapper;return vm.runInContext('genericActionPrompt(r,actor,actionRole,wrapper)',g.h.ctx);}
function cardRoles(g){return g.room.players.map(p=>g.room.currentCards.get(p.id).role)}
// Shield must survive all night interactions, including forged targets.
{
 const g=setup(['sentinel','robber','witch','seer','drunk','insomniac','village_idiot','curator','investigator','revealer','troublemaker','doppelganger','villager']);const ids=g.room.players.map(p=>p.id);act(g,0,'sentinel',{targets:[ids[1]]});assert(g.room.shields.has(ids[1]));
 for(const role of ['seer','robber','witch','troublemaker','investigator','revealer','curator','mystic_wolf','alpha_wolf']){assert(!prompt(g,0,role).others.some(p=>p.id===ids[1]));checks++;}
 for(const role of ['robber','drunk','insomniac']){const before=JSON.stringify([...g.room.currentCards]);act(g,1,role,role==='drunk'?{centerIndexes:[0]}:{targets:[ids[2]]});assert.equal(JSON.stringify([...g.room.currentCards]),before);assert(prompt(g,1,role).blocked);checks++;}
 assert.throws(()=>act(g,2,'robber',{targets:[ids[1]]}));assert.throws(()=>act(g,2,'seer',{type:'player',targets:[ids[1]]}));checks+=2;
 const protectedCard=g.room.currentCards.get(ids[1]),own=g.room.currentCards.get(ids[6]);act(g,6,'village_idiot',{direction:'right'});assert.equal(g.room.currentCards.get(ids[1]),protectedCard);assert.equal(g.room.currentCards.get(ids[6]),own);assert.equal(new Set([...g.room.currentCards.values(),...g.room.centerCards].map(c=>c.id)).size,13);checks++;
}
// Alpha's mandatory fourth center and Dream Wolf recognition.
{
 const g=setup(['alpha_wolf','dream_wolf','witch','seer','mystic_wolf','villager']);const ids=g.room.players.map(p=>p.id);assert.equal(g.room.centerCards.length,4);assert.equal(g.room.centerCards[3].role,'werewolf');assert(!prompt(g,0,'alpha_wolf').others.some(p=>p.id===ids[1]));act(g,0,'alpha_wolf',{targets:[ids[2]]});assert.equal(g.room.currentCards.get(ids[2]).role,'werewolf');assert.equal(g.room.centerCards[3].role,'witch');act(g,2,'witch',{centerIndexes:[3]});assert.throws(()=>act(g,2,'witch',{skip:true}));act(g,2,'witch',{targets:[ids[2]]});assert.equal(g.room.currentCards.get(ids[2]).role,'witch');checks+=4;
}
// Sequential investigator; physical faces, transformations move with cards.
for(const found of ['werewolf','alpha_wolf','mystic_wolf','dream_wolf','tanner','villager','doppelganger','investigator']){
 const g=setup(found==='investigator'?['investigator','villager','hunter','werewolf','tanner','robber']:['investigator',found,'hunter','robber','seer','villager']);const ids=g.room.players.map(p=>p.id),target=g.room.currentCards.get(ids[1]);if(found==='investigator')target.role='investigator';if(found==='doppelganger')target.doppelRole='werewolf';if(found==='investigator')target.piRole='werewolf';
 const result=act(g,0,'investigator',{targets:[ids[1]]});const expected=E.isWerewolf(found)?'werewolf':found==='tanner'?'tanner':null;assert.equal(g.room.players[0].initialCard.piRole||null,expected);assert.equal(!!result.nextPrompt,!expected);assert(!prompt(g,0,'investigator').others.some(p=>p.id===ids[1]));assert.equal(result.seen[0].role,found);if(!expected){act(g,0,'investigator',{targets:[ids[2]]});assert(!g.room.players[0].pendingReveal.nextPrompt)}checks+=4;
}
// Revealer uses physical card only, hides actual wolves and Tanner.
for(const found of ['werewolf','alpha_wolf','mystic_wolf','dream_wolf','tanner','doppelganger','investigator','bodyguard']){
 const g=setup(['revealer',found,'villager','robber','seer','hunter']),id=g.room.players[1].id,c=g.room.currentCards.get(id);if(found==='doppelganger')c.doppelRole='werewolf';if(found==='investigator')c.piRole='werewolf';act(g,0,'revealer',{targets:[id]});assert.equal(g.room.revealedCards.has(id),!E.isWerewolf(found)&&found!=='tanner');checks++;
}
// Every artifact: private event, overriding final card ability and reconnect.
for(const key of Object.keys(ARTIFACTS)){
 const g=setup(['curator','hunter','bodyguard','werewolf','seer','villager']);const id=g.room.players[1].id;g.room.artifactDeck=[key];act(g,0,'curator',{targets:[id]});assert(!prompt(g,0,'curator').others.some(p=>p.id===id));assert(!g.cs[1].take('artifact:reveal'));g.h.ctx.r=g.room;vm.runInContext('beginDiscussion(r)',g.h.ctx);assert.equal(g.cs[1].take('artifact:reveal').key,key);assert(!g.cs[0].take('artifact:reveal'));assert.equal(E.effectiveRole(vm.runInContext('outcomeCard(r,r.players[1].id)',g.h.ctx)),ARTIFACTS[key].role||'hunter');const tok=g.room.players[1].resumeToken;g.cs[1].disconnect();const fresh=g.h.client('R');assert(fresh.call('room:resume',{code:g.code,resumeToken:tok}).ok);assert.equal(fresh.take('artifact:reveal').key,key);assert(g.room.artifacts.has(fresh.id));assert(!g.room.artifacts.has(id));checks+=7;
}
// Independent death oracle: bodyguards exclude protected targets, then hunters chain.
function deathOracle(players,roles){const protectedIds=new Set(players.filter((p,i)=>roles[i]==='bodyguard').map(p=>p.vote)),counts={};players.forEach(p=>{if(!protectedIds.has(p.vote))counts[p.vote]=(counts[p.vote]||0)+1});const max=Math.max(0,...Object.values(counts)),dead=new Set(max<2?[]:Object.keys(counts).filter(id=>counts[id]===max));let change=true;while(change){change=false;players.forEach((p,i)=>{if(dead.has(p.id)&&roles[i]==='hunter'&&!protectedIds.has(p.vote)&&!dead.has(p.vote)){dead.add(p.vote);change=true}})}return [...dead].sort();}
let seed=1091;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296},pick=a=>a[Math.floor(rand()*a.length)];
for(let t=0;t<25000;t++){const n=3+t%8,roles=Array.from({length:n},()=>pick(['bodyguard','hunter','werewolf','alpha_wolf','mystic_wolf','dream_wolf','villager','minion','tanner'])),players=roles.map((_,i)=>({id:'p'+i,name:'P'+i,vote:'p'+pick(Array.from({length:n},(_,j)=>j).filter(j=>j!==i))})),cards=roles.map((r,i)=>E.makeCard(r,'c'+i));if(t%3===0)cards[0].artifactRole=pick(['werewolf','villager','tanner']);const final=cards.map(E.effectiveRole);assert.deepEqual(E.computeDeathsWithHunter(players,id=>cards[+id.slice(1)]).sort(),deathOracle(players,final));const result=E.resolveOutcome(players,id=>cards[+id.slice(1)]);const deadWolf=players.some((p,i)=>E.isWerewolf(final[i])&&result.killedIds.includes(p.id));if(deadWolf)assert(result.winningTeams.includes('village'));assert(!result.winnerIds.some(id=>final[+id.slice(1)]==='tanner'&&!result.killedIds.includes(id)));checks++;}
// Full games and all Doppelgänger expansion branches, including natural bots.
function play(deck,copyRole=null,bots=false,timeout=false){const g=setup(deck,seed++,bots);if(bots&&copyRole){g.h.ctx.force=copyRole;g.h.ctx.r=g.room;vm.runInContext("const oldBot=botNightPayload;botNightPayload=p=>p.stage==='copy'?{targets:[p.others.find(x=>r.players.find(y=>y.id===x.id).initialCard.role===force).id]}:oldBot(p)",g.h.ctx);}g.cs.forEach(c=>c.call('role:ready'));let guard=0;while(g.room.phase==='night'){
 assert(++guard<10000,'No stalled night');if(g.room.narrationCue)g.cs[0].call('narration:done',{cueId:g.room.narrationCue.cueId});else if(g.room.actionWindowOpen){if(timeout){const step=g.room.activeNightRole;g.h.advance(9999);assert.equal(g.room.activeNightRole,step);g.h.advance(1);assert.equal(g.room.pendingActors.size,0);assert.equal(g.room.awaitingAck.size,0);checks+=3;}else{for(const c of g.cs){if(g.room.awaitingAck.has(c.id)){c.call('night:ack');continue;}if(!g.room.pendingActors.has(c.id))continue;const p=c.take('night:prompt');let payload={};coverage.add(p.actionRole);if(p.blocked)payload={};else if(p.stage==='copy'){const target=p.others.find(x=>g.room.players.find(y=>y.id===x.id).initialCard.role===copyRole)||p.others[0];payload={targets:[target.id]};copies.add(g.room.players.find(y=>y.id===target.id).initialCard.role);}else if(p.input==='direction')payload={direction:pick(['left','right'])};else if(p.input==='center')payload={centerIndexes:[pick(p.center)]};else if(p.input==='player')payload={targets:[pick(p.others).id]};else if(p.actionRole==='seer')payload={type:'center',centerIndexes:[p.center[0],p.center.at(-1)]};else if(p.actionRole==='robber')payload={targets:[p.others[0].id]};else if(p.actionRole==='troublemaker')payload=p.others.length>=2?{targets:p.others.slice(0,2).map(x=>x.id)}:{skip:true};else if(p.actionRole==='drunk'||p.actionRole==='werewolf'&&p.solo&&p.loneWolfCenter)payload={centerIndexes:[p.center.at(-1)]};const res=c.call('night:action',payload);assert(res?.ok,JSON.stringify({p,res}));}g.h.advance(100);}}
 else g.h.advance(100);
 }
 assert.equal(g.room.phase,'discussion');const cards=[...g.room.currentCards.values(),...g.room.centerCards];assert.equal(new Set(cards.map(c=>c.id)).size,cards.length);assert.equal(cards.length,deck.length+(deck.includes('alpha_wolf')?1:0));for(const c of g.cs){const pub=c.take('room:update');assert(!JSON.stringify(pub).includes('doppelRole'));assert(!Object.keys(pub).includes('artifacts'));}g.cs[0].call('discussion:endEarly');if(bots)g.h.advance(200);for(const c of g.cs)assert(c.call('vote:cast',{targetId:g.room.players.find(p=>p.id!==c.id).id}).ok);assert.equal(g.room.phase,'result');const result=g.cs[0].take('game:result');assert(result.players.every(p=>p.final));assert.equal(result.center.length,g.room.centerCards.length);g.cs[0].call('game:restart');assert.equal(g.room.phase,'lobby');assert.equal(g.room.artifacts.size,0);assert.equal(g.room.shields.size,0);assert.equal(g.room.revealedCards.size,0);games++;return g;}
function fill(initial,n){const deck=[...initial],pool=Object.keys(E.ROLE_INFO).filter(k=>k!=='mason').flatMap(k=>Array(E.ROLE_INFO[k].max).fill(k));for(const k of deck)pool.splice(pool.indexOf(k),1);while(deck.length<n+3)deck.push(pool.shift());assert(E.validateRoleSelection(deck,n).ok);return deck;}
for(const role of Object.keys(DAYBREAK_ROLES)){play(fill(['doppelganger',role,'villager'],10),role);play(fill(['villager','doppelganger',role],10),role,true);}
for(let i=0;i<300;i++){const n=3+i%8,available=Object.keys(E.ROLE_INFO).filter(k=>k!=='mason').flatMap(k=>Array(E.ROLE_INFO[k].max).fill(k)),deck=[];while(deck.length<n+3)deck.push(available.splice(Math.floor(rand()*available.length),1)[0]);if(!E.validateRoleSelection(deck,n).ok){i--;continue;}play(deck,null,i%2===0);}
for(const role of ['alpha_wolf','witch','investigator','village_idiot','curator','revealer','sentinel'])play(fill(['doppelganger',role,'villager'],10),role,false,true);
for(const role of Object.keys(DAYBREAK_ROLES).filter(k=>!['bodyguard','dream_wolf'].includes(k)))assert(coverage.has(role),'Missing action '+role);for(const role of Object.keys(DAYBREAK_ROLES))assert(copies.has(role),'Missing copy '+role);
console.log(JSON.stringify({daybreakChecks:checks,fullGames:games,roles:[...coverage],doppelCopies:[...copies]},null,2));

