'use strict';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={w:'흰색',b:'파랑',g:'초록',r:'빨강',k:'검정',p:'진주',y:'금',x:'복사'};
const C=['w','b','g','r','k'];const ALL=[...C,'p','y'];
const abilityText={again:'↻ 추가 턴',copy:'🌈 색상 복사',gem:'◆ 보석 획득',priv:'📜 특권',steal:'⇄ 상대 토큰 강탈'};
let S=null, session=null,events=null,mode='take',indices=[],reserveGold=null,buyTarget=null,payment=null,colorPick=null,busy=false;
let saved=null;try{saved=JSON.parse(localStorage.getItem('jewel-duel-session')||'null')}catch(e){}
const codeFromPath=(location.pathname.match(/\/room\/([A-HJ-NP-Z2-9]{6})$/)||[])[1]||'';
function toast(msg){const el=$('#toast');el.textContent=msg;el.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>el.style.display='none',3600)}

function gem(c,num='',size=''){const inner=size!==''?size:'';return `<span class="gemwrap"><span class="gem ${esc(c)}" title="${labels[c]||c}">${inner}</span>${num!==''?`<span class="dot">${num}</span>`:''}</span>`}
function resources(ts){return ALL.map(c=>(ts?.[c]?gem(c,ts[c]):'')).join('')||'<span class="small">없음</span>'}

function ownBonuses(bs){return C.map(c=>(bs[c]?gem(c,bs[c]):'')).join('')||'<span class="small">없음</span>'}
function powerCells(p){return [...C,'p','y'].map(c=>{const tok=p.tokens?.[c]||0, bonus=(c==='p'||c==='y'?0:(p.bonus?.[c]||0)), total=tok+bonus;return `<div class="power-pill ${c}"><div class="power-top">${gem(c,'')}</div><div class="power-main">${total}</div><div class="power-sub">${c==='y'?'금 '+tok:(c==='p'?`진주 ${tok}`:`${tok} + ${bonus}`)}</div></div>`}).join('')}
function bonusSummary(p){return C.map(c=>`<span class="bonus-mini">${gem(c,'')}<strong>${p.bonus[c]||0}</strong><small>★${p.colorPoints[c]||0}</small></span>`).join('')}
function playerPanel(v,i){const mine=S.seat===i;const active=S.turn===i;const totalTokens=Object.values(v.tokens).reduce((a,b)=>a+b,0);return `<div class="player-panel ${mine?'mine':''} ${active?'active':''}"><div class="panel-head"><div><div class="panel-label">${mine?'내 정보':'상대 정보'}</div><div class="pname">${esc(v.name)} ${v.isBot?'🤖':v.connected?'🟢':'⚪'}</div></div><div class="stat-badges"><span class="stat">★ ${v.score}</span><span class="stat">👑 ${v.crowns}</span><span class="stat">📜 ${v.priv}</span></div></div><div class="mini">큰 숫자 = 지금 쓸 수 있는 총량 · 아래 = 보석 + 할인${mine?'':" · 상대도 동일 표시"}</div><div class="power-grid">${powerCells(v)}</div><div class="substats"><span>예약 ${v.reserved.length}/3</span><span>보유 토큰 ${totalTokens}개</span><span>구매 카드 ${v.owned.length}장</span></div></div>`}

function cardView(id,opts={}){if(!id)return `<div class="card-slot">빈 자리</div>`;const cd=S.cardData[id];if(!cd)return '';
 const cost=Object.entries(cd.k).map(([c,n])=>`<span class="costtag"><span class="gem ${c}"></span><strong>${n}</strong></span>`).join('')||'<span class="smallcost">비용 없음</span>';
 const a=cd.a.map(x=>({again:'추가 턴',gem:'보석 +1',priv:'특권 +1',steal:'강탈',copy:'복사'}[x]||x)).join(' · ');
 const bonus=Object.entries(cd.b).map(([c,n])=>c==='x'?`🌈 복사`:`${gem(c,'')} ${n}`).join('')||'보너스 없음';
 const levelLabel=['','Ⅰ','Ⅱ','Ⅲ'][cd.l]||cd.l;
 let data=opts.target?`data-act="card" data-zone="${opts.target.zone}" data-l="${opts.target.level||0}" data-i="${opts.target.index}"`:'';
 return `<button class="card" data-color="${cd.c}" ${data} title="${cd.l}단계 · ${cd.p}점 · 왕관 ${cd.n} · ${Object.entries(cd.k).map(([c,n])=>labels[c]+n).join(', ')}" ${opts.disabled?'disabled':''}><div class="card-topline"><span class="badge level">${levelLabel}</span><span class="badge score">★${cd.p}</span></div><div class="card-main"><div class="card-bonusline"><span class="bonus-chip">${bonus}</span>${cd.n?`<span class="crown-chip">👑${cd.n}</span>`:''}</div>${a?`<div class="card-abilities">${a.split(' · ').map(x=>`<span class="ability-chip">${x}</span>`).join('')}</div>`:''}</div><div class="card-costtitle">비용</div><div class="card-cost">${cost}</div></button>`}
async function request(url,body){const opts=body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{};const res=await fetch(url,opts);const j=await res.json();if(!res.ok)throw Error(j.error||'서버 오류');return j}
async function move(action){if(!session||busy)return;busy=true;try{await request('/api/action',{...session,action});indices=[];reserveGold=null} catch(e){toast(e.message)}finally{busy=false}}
function conn(text,online){$('#conn').innerHTML=`<span class="net ${online?'':'down'}"></span>${esc(text)}`}
function connect(){if(events){events.close();events=null}if(!session)return;conn('연결 중',false);
 const q=new URLSearchParams({code:session.code,token:session.token});
 request('/api/state?'+q.toString()).then(s=>{S=s;render()}).catch(e=>{toast(e.message);localStorage.removeItem('jewel-duel-session');session=null;S=null;render()});
 events=new EventSource('/api/events?'+q.toString());events.addEventListener('open',()=>conn('연결됨',true));events.addEventListener('state',e=>{try{S=JSON.parse(e.data);conn('연결됨',true);render()}catch(err){console.error(err)}});events.addEventListener('error',()=>conn('재연결 중',false));}
function saveSession(s){session=s;localStorage.setItem('jewel-duel-session',JSON.stringify(s));history.replaceState({},'',`/room/${s.code}`);connect()}
function lobby(){return `<section class="box join"><div class="gold">✦ GEMSTONE SOCIETY</div><h1>보석 듀얼</h1><p class="intro">두 사람이 각자의 휴대폰으로 접속해 보석을 모으고 카드를 구매하는 실시간 전략 게임입니다. 회원가입 없이 방 코드로 시작하세요.</p><label for="nick">플레이어 이름</label><input id="nick" maxlength="16" placeholder="닉네임" autocomplete="nickname" value=""/><button class="button primary" style="width:100%;margin-top:10px" data-act="createbot">🤖 봇과 혼자 플레이</button><button class="button secondary" style="width:100%;margin-top:9px" data-act="create">＋ 친구 대전 방 만들기</button><div class="thin"></div><label for="roomcode">친구의 방 코드</label><input id="roomcode" maxlength="6" placeholder="예: JD7K2M" value="${esc(codeFromPath)}" style="letter-spacing:3px;text-transform:uppercase"/><button class="button" style="width:100%;margin-top:10px" data-act="join">방 코드로 입장하기</button><p class="hint">공식 규칙을 구현한 개인용 비공식 웹게임입니다. 카드 일러스트는 자체 제작 UI로 대체했습니다.</p></section>`}
function waiting(){const p=S.players;return `<section class="box" style="margin-top:20px;text-align:center"><p class="muted">친구에게 이 코드나 링크를 보내세요</p><div class="code" style="margin:14px">${S.code}</div><button class="button secondary" data-act="share">링크 복사하기</button><hr class="sep"/><h2>입장 현황</h2><div class="scoregrid">${[0,1].map(i=>`<div class="soft" style="min-height:80px"><strong>${esc(p[i]?.name||'친구 기다리는 중')}</strong><div class="hint">${p[i]?'입장 완료 ✓':'대기 중...'}</div></div>`).join('')}</div><p class="hint">방장은 두 명이 들어오면 시작할 수 있어요. 시작 플레이어는 무작위로 정해집니다.</p>${S.seat===0?`${p.length===1?`<button data-act="addbot" class="button primary" style="margin-top:16px;width:100%">🤖 봇을 추가하고 게임 시작</button>`:''}<button data-act="start" class="button secondary" style="margin-top:10px;width:100%" ${p.length!==2?'disabled':''}>두 명 게임 시작</button>`:'<div class="note" style="margin-top:16px">방장이 게임을 시작하기를 기다리고 있어요.</div>'}<p class="hint" style="margin-top:15px"><button data-act="leave" class="button secondary">방 나가기</button></p></section>`}

function statusHTML(){const me=S.players[S.seat],opp=S.players[1-S.seat];const oppIndex=1-S.seat;return `<section class="status-stack"><div class="focus-note"><strong>내 구매력</strong> · 큰 숫자는 토큰과 카드 할인을 합친 값입니다.</div>${playerPanel(me,S.seat)}<details class="rival-details"><summary><span><strong>상대 ${esc(opp.name)}</strong> ${opp.connected?'🟢':'⚪'}</span><span>★${opp.score}　👑${opp.crowns}　📜${opp.priv}　⌄</span></summary>${playerPanel(opp,oppIndex)}</details></section>`}
function victoryMeter(label,current,goal,kind){
 const pct=Math.max(0,Math.min(100,current/goal*100));
 return `<div class="victory-meter"><div class="victory-meter-label"><span>${label}</span><strong>${current}<small>/${goal}</small></strong></div><div class="victory-track" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${goal}" aria-valuenow="${Math.min(current,goal)}"><span class="victory-fill ${kind}" style="width:${pct}%"></span></div></div>`;
}
function victoryPlayer(p,mine){
 const scores=p.colorPoints||{};
 const best=Math.max(0,...C.map(c=>scores[c]||0));
 const bestColor=best?C.find(c=>scores[c]===best):null;
 const colorInfo=bestColor?`${labels[bestColor]} ${best}점`:'아직 0점';
 const colorCells=C.map(c=>`<div class="victory-color-item" title="${labels[c]} 카드 점수 ${scores[c]||0}점"><span class="gem ${c}" aria-hidden="true"></span><b>${scores[c]||0}</b></div>`).join('');
 return `<div class="victory-player ${mine?'mine':'rival'}"><div class="victory-player-title"><strong title="${esc(p.name)}">${mine?'나':esc(p.name)}</strong><span>${mine?'내 기록':p.isBot?'🤖 봇':'상대 기록'}</span></div>
 ${victoryMeter('총점',p.score,20,'points')}${victoryMeter('왕관',p.crowns,10,'crowns')}${victoryMeter('단색 최고',best,10,'colors')}
 <div class="victory-color-title">색상별 카드 점수 <span>${colorInfo}</span></div><div class="victory-colors" aria-label="${mine?'내':'상대'} 색상별 카드 점수">${colorCells}</div></div>`;
}
function victoryStatusHTML(){const me=S.players[S.seat],opp=S.players[1-S.seat];return `<section class="box victory-section" id="victory"><h2>승리 진행 상황 <span class="chip">★20 / 👑10 / 단색 ★10</span></h2><div class="victory-compare">${victoryPlayer(me,true)}${victoryPlayer(opp,false)}</div></section>`}
function summary(){const mine=S.players[S.seat],opp=S.players[1-S.seat];let isMine=S.turn===S.seat;
 if(S.phase==='over')return `🏆 ${esc(S.players[S.winner].name)}님의 승리!`;
 if(!isMine)return opp.isBot?'🤖 봇이 다음 수를 계산하고 있어요. 잠시 기다려 주세요.':`상대 ${esc(opp.name)}님이 행동하는 중입니다.`;
 return ({main:mode==='reserve'?'① 금 토큰을 누르고 ② 예약할 카드 또는 덱을 선택':mode==='priv'?'특권으로 가져올 보석/진주를 탭하세요.':`보석 최대 3개를 가로·세로·대각선 한 줄로 선택하세요.`,gem:`카드 효과: ${labels[S.effectColor]} 보석을 하나 골라 주세요.`,steal:'카드 효과: 상대방이 가진 금 이외 토큰을 선택하세요.',royal:'왕관 보상: 왕실 카드 한 장을 선택하세요.',discard:'토큰이 10개가 될 때까지 돌려놓으세요.'})[S.phase]||''}

function marketHTML(){const me=S.players[S.seat];return `<section class="box" id="market"><h2>보석 카드 시장 <span class="chip">카드를 눌러 구매 · 예약</span></h2><div class="soft market-power"><div class="small">내 구매력 요약 · 큰 숫자 기준으로 카드 비용을 보면 편해요</div><div class="power-grid compact">${powerCells(me)}</div></div>${[3,2,1].map(l=>`<div class="market-line"><div class="title-line"><span class="small">LEVEL ${l} · 남은 덱 ${S.deckCounts[l]}장</span></div><div class="market-row l${l}">${S.market[l].map((id,i)=>cardView(id,{target:{zone:'market',level:l,index:i}})).join('')}</div></div>`).join('')}<div class="decks">${[1,2,3].map(l=>`<button class="deckbtn" data-act="deck" data-l="${l}" ${S.deckCounts[l]===0?'disabled':''}>${l}단계 덱 ▣ ${S.deckCounts[l]}</button>`).join('')}</div><p class="hint">덱 맨 위 카드는 예약 모드에서만 비공개로 가져갈 수 있어요.</p></section>`}

function boardHTML(){const isMine=S.turn===S.seat;let buttonDisabled=!isMine||S.phase!=='main';const highlights=S.phase==='gem'?S.board.map((v,i)=>v===S.effectColor?i:-1).filter(i=>i>=0):(mode==='priv'?S.board.map((v,i)=>v&&v!=='y'?i:-1).filter(i=>i>=0):[]);
 return `<section class="box" id="board"><h2>공용 보석판 <span class="chip">주머니 ${S.bagCount}개</span></h2><div class="board">${S.board.map((c,i)=>`<button aria-label="${i}번째 칸 ${labels[c]||'비어있음'}" data-act="cell" data-i="${i}" class="cell ${c?'':'empty'} ${indices.includes(i)||reserveGold===i?'selected':''} ${highlights.includes(i)&&isMine?'highlight':''}" ${!isMine&&S.phase==='main'?'disabled':''}>${c?gem(c,'',''):''}${indices.includes(i)?`<span class="number">${indices.indexOf(i)+1}</span>`:''}</button>`).join('')}</div><p class="note" style="margin-bottom:10px">${esc(summary())}</p><div class="actions"><button class="button ${mode==='take'?'selected':''}" data-act="mode" data-mode="take" ${buttonDisabled?'disabled':''}>보석 가져오기</button><button class="button ${mode==='reserve'?'selected':''}" data-act="mode" data-mode="reserve" ${buttonDisabled?'disabled':''}>카드 예약</button><button class="button ${mode==='priv'?'selected':''}" data-act="mode" data-mode="priv" ${buttonDisabled||S.refilled||!S.players[S.seat].priv?'disabled':''}>특권 사용</button><button class="button" data-act="refill" ${buttonDisabled||S.refilled||S.bagCount===0||!S.board.includes(null)?'disabled':''}>보드 보충</button></div>${S.phase==='main'&&isMine&&mode==='take'?`<button class="button primary" style="margin-top:8px;width:100%" data-act="take" ${!indices.length?'disabled':''}>선택한 보석 ${indices.length}개 가져오기</button>`:''}</section>`}
function royalHTML(){let can=S.turn===S.seat&&S.phase==='royal';return `<section class="box" id="royal"><h2>왕실 카드 <span class="chip">왕관 3 · 6개 도달 시 획득</span></h2><div class="royal-row">${S.royalData.map(r=>`<button class="royal ${S.royals.includes(r.id)?'':'disabled'}" data-act="royal" data-i="${r.id}" ${!can||!S.royals.includes(r.id)?'disabled':''}><strong>👑</strong>★${r.p} ${r.a?abilityText[r.a]||'':''}</button>`).join('')}</div></section>`}

function ownershipHTML(){const my=S.players[S.seat],opp=S.players[1-S.seat];
 const ownedRow=(arr,targetZone='reserved')=>arr.length?`<div class="cardstrip">${arr.map((item,i)=>{const id=typeof item==='string'?item:item.id;const target=targetZone==='reserved'?{zone:'reserved',index:i}:null;return cardView(id,target?{target}:{});}).join('')}</div>`:'<div class="soft small">없음</div>';
 const oppOwned=opp.owned.length?`<div class="cardstrip readonly">${opp.owned.map(x=>cardView(x.id,{})).join('')}</div>`:'<div class="soft small">없음</div>';
 return `<section class="box" id="owned"><h2>보유 카드 · 예약 카드</h2><div class="bonus-summary-grid"><div class="soft"><h3>내 할인 / 단색 점수</h3><div class="bonus-summary">${bonusSummary(my)}</div></div><div class="soft"><h3>상대 할인 / 단색 점수</h3><div class="bonus-summary">${bonusSummary(opp)}</div></div></div><h3 style="margin-top:12px">내 예약 카드</h3>${ownedRow(my.reserved,'reserved')}<h3 style="margin-top:12px">내가 구매한 카드</h3><div class="cardstrip readonly">${my.owned.map(x=>cardView(x.id,{})).join('')||''}</div><h3 style="margin-top:12px">상대가 구매한 카드</h3>${oppOwned}</section>`}
function effectsHTML(){if(S.turn!==S.seat||S.phase==='main'||S.phase==='over')return '';
 if(S.phase==='steal'){const opponent=S.players[1-S.seat].tokens;return `<section class="box"><h2>상대 토큰 강탈</h2><div class="choices">${[...C,'p'].map(c=>`<button data-act="steal" data-color="${c}" class="button" ${!opponent[c]?'disabled':''}>${gem(c)} ${opponent[c]}개</button>`).join('')}</div></section>`}
 if(S.phase==='discard'){const player=S.players[S.seat].tokens;return `<section class="box"><h2>보유 토큰 정리 (10개 제한)</h2><div class="choices">${ALL.map(c=>`<button data-act="discard" data-color="${c}" class="button" ${!player[c]?'disabled':''}>${gem(c)} ${player[c]}개 반환</button>`).join('')}</div></section>`}
 if(S.phase==='royal')return `<section class="note">아래 왕실 카드 4종 중 남아 있는 한 장을 눌러 선택하세요.</section>`;
 if(S.phase==='gem')return `<section class="note">보드에서 획득할 같은 색 보석을 골라 주세요.</section>`;return ''}

function gameplay(){const me=S.players[S.seat];return `${statusHTML()}${victoryStatusHTML()}${effectsHTML()}${S.phase==='over'?`<section class="box finish">🎉 <strong>${esc(S.players[S.winner].name)}님이 승리했습니다!</strong><div class="hint">★${S.players[S.winner].score} · 👑${S.players[S.winner].crowns}</div></section>`:''}${boardHTML()}${marketHTML()}${royalHTML()}${ownershipHTML()}<section class="box"><h2>게임 기록</h2>${S.logs.map(x=>`<div class="log">${esc(x)}</div>`).join('')}</section><p class="hint" style="text-align:center">비공식 팬 구현 · 원작 규칙에 기반 · 그림은 자체 제작</p>`}
function bottomHTML(){if(!S?.started)return '';let playing=S.turn===S.seat;return `<div class="bottom-inner"><div class="grow"><strong>${S.phase==='over'?'게임 종료':playing?'내 차례':'상대방 차례'}</strong><div class="sticky-msg">방 ${S.code} · ${S.phase==='main'?'일반 행동':({gem:'같은 색 선택',royal:'왕실 선택',steal:'토큰 강탈',discard:'10개 이하로 반환',over:'승리'})[S.phase]}</div></div><button class="button secondary" data-act="share" style="min-height:36px;padding:7px 10px">초대 링크</button><button class="button secondary" data-act="goto" data-id="board" style="min-height:36px;padding:7px 10px">보드 ↑</button></div>`}
function render(){const a=$('#app'),b=$('#bottom');if(!session){a.innerHTML=lobby();b.classList.add('off');return}if(!S){a.innerHTML='<section class="box">게임에 연결하고 있습니다...</section>';return}a.innerHTML=!S.started?waiting():gameplay();b.classList.toggle('off',!S.started);b.innerHTML=S.started?bottomHTML():'';if(buyTarget)paintModal()}
function findCard(target){if(!S)return null;return target.zone==='reserved'?S.players[S.seat].reserved[target.index]:(target.zone==='market'?S.market[target.level][target.index]:null)}
function payDue(cd){const bs=S.players[S.seat].bonus;return Object.fromEntries(Object.entries(cd.k).map(([c,n])=>[c,Math.max(0,n-(c==='p'?0:bs[c]))]))}
function openBuy(target){const id=findCard(target);if(!id)return;const cd=S.cardData[id];buyTarget=target;const required=payDue(cd),have=S.players[S.seat].tokens;payment={};for(const [c,n] of Object.entries(required))payment[c]=Math.min(n,have[c]);payment.y=Object.entries(required).reduce((sum,[c,n])=>sum+n-payment[c],0);colorPick=C.find(c=>S.players[S.seat].bonus[c]>0)||null;paintModal()}
function payRows(cd){const req=payDue(cd),have=S.players[S.seat].tokens;const goldNeeded=Object.entries(req).reduce((sum,[c,n])=>sum+n-(payment[c]||0),0);payment.y=goldNeeded;return {goldNeeded,html:Object.entries(req).map(([c,n])=>`<div class="payrow"><div>${gem(c)} 필요한 수량 <strong>${n}</strong><div class="mini">보유 ${have[c]}개</div></div><div class="step"><button data-act="pay" data-color="${c}" data-dir="-1" ${!payment[c]?'disabled':''}>−</button><strong>${payment[c]||0}</strong><button data-act="pay" data-color="${c}" data-dir="1" ${payment[c]>=Math.min(n,have[c])?'disabled':''}>+</button></div></div>`).join('')}}
function paintModal(){const m=$('#modal');if(!buyTarget||!S){m.innerHTML='';return}const cd=S.cardData[findCard(buyTarget)];if(!cd){closeModal();return}const me=S.players[S.seat],mine=S.turn===S.seat&&S.phase==='main';const pay=payRows(cd);const valid=pay.goldNeeded<=me.tokens.y&&(!cd.b.x||colorPick&&me.bonus[colorPick]>0);
 m.innerHTML=`<div class="overlay" data-act="overlay"><div class="sheet" role="dialog" aria-modal="true"><div class="row between"><strong>LEVEL ${cd.l} · ${cd.id}</strong><button class="button secondary" data-act="close">✕</button></div><div class="row" style="margin:10px 0;align-items:start"><div style="width:94px;flex-shrink:0">${cardView(cd.id)}</div><div class="grow"><div class="gold" style="font-size:19px">★${cd.p} · 👑${cd.n}</div><div class="hint">지속 보너스: ${Object.entries(cd.b).map(([c,n])=>`${labels[c]} ${n}`).join(', ')||'없음'}</div><div class="hint">효과: ${cd.a.map(a=>abilityText[a]).join(' · ')||'없음'}</div><div class="hint">공개된 카드와 내 예약 카드는 본인 턴에 구매할 수 있어요.</div></div></div>${cd.b.x?`<div class="soft"><h3>색상 복사 (보유한 보너스 색으로 선택)</h3><div class="choices">${C.map(c=>`<button class="button ${colorPick===c?'selected':''}" data-act="copycolor" data-color="${c}" ${!me.bonus[c]?'disabled':''}>${gem(c)} ${me.bonus[c]}</button>`).join('')}</div></div>`:''}<h3 style="margin:13px 0 5px">보석 지불 방식</h3>${pay.html}<div class="payrow"><div>${gem('y')} 만능 금 <strong>${pay.goldNeeded}개 필요</strong></div><div class="small">보유 ${me.tokens.y}개</div></div><p class="hint">색 보석 대신 금 토큰을 내고 싶다면 − 버튼으로 줄이세요.</p><button class="button primary" style="margin-top:13px;width:100%" data-act="confirmbuy" ${!mine||!valid?'disabled':''}>${!mine?'지금은 내 차례가 아니에요':valid?'이 구성으로 구매하기':'구매 조건이 충족되지 않았어요'}</button></div></div>`}
function closeModal(){buyTarget=null;payment=null;$('#modal').innerHTML=''}
const targetFrom=(el)=>({zone:el.dataset.zone,level:Number(el.dataset.l),index:Number(el.dataset.i)});
function isTurn(){return S&&S.started&&S.turn===S.seat&&S.phase!=='over'}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-act]');if(!el)return;const act=el.dataset.act;
 try{
 if(act==='create'||act==='join'||act==='createbot'){const name=$('#nick')?.value||'플레이어';let out=act==='create'?await request('/api/create',{name}):act==='createbot'?await request('/api/create-bot',{name}):await request('/api/join',{code:$('#roomcode').value.trim().toUpperCase(),name});saveSession(out);return}
 if(act==='addbot'){await request('/api/add-bot',session);return}
 if(act==='start'){await request('/api/start',session);return}
 if(act==='leave'){await request('/api/leave',session);localStorage.removeItem('jewel-duel-session');session=null;S=null;if(events)events.close();history.replaceState({},'','/');render();return}
 if(act==='share'){const url=`${location.origin}/room/${session.code}`;if(navigator.share){try{await navigator.share({title:'보석 듀얼',text:`방 코드 ${session.code}`,url});return}catch(err){}}try{await navigator.clipboard.writeText(url);toast('초대 링크를 복사했어요.')}catch(e){window.prompt('초대 링크를 복사하세요',url)}return}
 if(act==='goto'){document.getElementById(el.dataset.id)?.scrollIntoView({behavior:'smooth'});return}
 if(act==='close'){closeModal();return}if(act==='overlay'){if(e.target===el)closeModal();return}
 if(act==='pay'&&buyTarget){const cd=S.cardData[findCard(buyTarget)];const c=el.dataset.color,dir=Number(el.dataset.dir),r=payDue(cd),limit=Math.min(r[c]||0,S.players[S.seat].tokens[c]);payment[c]=Math.max(0,Math.min(limit,payment[c]+dir));paintModal();return}
 if(act==='copycolor'){colorPick=el.dataset.color;paintModal();return}
 if(act==='confirmbuy'){const t=buyTarget;const chosen=colorPick;const pay={...payment};closeModal();await move({type:'buy',target:t,color:chosen,payment:pay});return}
 if(!isTurn())return;
 if(act==='mode'){mode=el.dataset.mode;indices=[];reserveGold=null;render();document.getElementById('board')?.scrollIntoView({block:'nearest'});return}
 if(act==='refill'){await move({type:'refill'});return}
 if(act==='cell'){const i=Number(el.dataset.i);if(S.phase==='gem'){await move({type:'gem',index:i});return}if(S.phase!=='main')return;const c=S.board[i];if(!c)return;
  if(mode==='priv'){await move({type:'priv',index:i});return}
  if(mode==='reserve'){if(c!=='y'){toast('예약하려면 황금 토큰을 선택해야 해요.');return}reserveGold=i;render();return}
  if(c==='y'){toast('금은 카드 예약으로만 가져올 수 있어요.');return}
  if(indices.includes(i))indices=indices.filter(x=>x!==i);else if(indices.length<3)indices.push(i);else{toast('한 번에 최대 3개까지 선택할 수 있어요.');return}render();return}
 if(act==='take'){await move({type:'take',indices:[...indices]});return}
 if(act==='card'){const t=targetFrom(el);if(S.phase!=='main')return;if(t.zone==='reserved'){openBuy(t);return}if(mode==='reserve'){if(reserveGold===null){toast('먼저 공용 보석판에서 금 토큰을 선택하세요.');return}await move({type:'reserve',gold:reserveGold,target:t});return}openBuy(t);return}
 if(act==='deck'){if(mode!=='reserve'){toast('덱 맨 위 카드는 예약할 때만 가져올 수 있어요.');return}if(reserveGold===null){toast('먼저 금 토큰을 선택하세요.');return}await move({type:'reserve',gold:reserveGold,target:{zone:'deck',level:Number(el.dataset.l)}});return}
 if(act==='steal'){await move({type:'steal',color:el.dataset.color});return}
 if(act==='discard'){await move({type:'discard',color:el.dataset.color});return}
 if(act==='royal'){await move({type:'royal',id:Number(el.dataset.i)});return}
 }catch(err){toast(err.message);console.error(err)}});
window.addEventListener('storage',e=>{if(e.key==='jewel-duel-session'&&!e.newValue){if(events)events.close();session=null;S=null;render()}});
if(saved?.token&&saved?.code){session=saved;connect()}else{conn('준비됨',false);render()}